# Generated by Django 6.0.6 on 2026-07-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('Designation', models.CharField(max_length=100)),
                ('employee_salary', models.IntegerField()),
                ('date_of_joining', models.DateField()),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.AlterModelTable(
            name='admission',
            table='admission',
        ),
    ]
