# Generated by Django 6.0.6 on 2026-07-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_options_alter_student_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
