# Generated by Django 6.0.6 on 2026-08-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_class_student_student_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=10),
        ),
    ]
