# Generated by Django 6.0.6 on 2026-08-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_student',
            field=models.CharField(max_length=10),
        ),
    ]
