# Generated by Django 6.0.6 on 2026-08-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_class_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
