# Generated by Django 6.0.6 on 2026-09-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('subjects', models.CharField(max_length=100)),
                ('Assigned_class', models.CharField(max_length=100)),
            ],
        ),
    ]
