# Generated by Django 6.0.6 on 2026-09-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
