# Generated by Django 6.0.6 on 2026-09-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_teachers_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('message_type', models.CharField(max_length=50)),
                ('sceduled_date', models.DateField(blank=True, null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='notifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
